# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 111
    min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /api

# mysql
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）

renren:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: true # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.quasar.backend.entity
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 0
      table-underline: true
      field-strategy: 2
      id-type: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  level: info
  level.org.springframework.web: info
  level.com.quasar.backend: debug
  file:
    name: app.log
    path: logs/
