# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    min-spare-threads: 200
  port: 8087


#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/opsbackend?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
#    username: root
#    password: 123456
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#      enabled: true

logging:
  level: info
  level.org.springframework.web: info
  level.com.quasar.backend: debug
  file:
    name: app.log
    path: logs/
